name: Build Docker Image for Auto-generating Release Notes and Push to GitHub Packages

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: alpine-3.19-for-release-notes-gen
  DOCKER_IMAGE_TAG: 3.19-latest
  DOCKER_FILE: Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        cd release-notes-gen
        docker build \
                -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} \
                -f ${{ env.DOCKER_FILE }}

    # 동일한 태그로 이미지를 푸시하면, GitHub Packages에 있는 기존 이미지는 'untagged' 상태로 변경됨.
    - name: Push Docker image to GitHub Packages
      run: |
        TARGET_IMAGE=ghcr.io/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
        docker tag ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} $TARGET_IMAGE
        docker push $TARGET_IMAGE
